import {randomUUID} from "node:crypto";import {query,type D1Row} from "./database";import type {Birthday,Gift,PublicBirthday,PublicGift} from "./types";
const str=(r:D1Row,k:string)=>typeof r[k]==="string"?r[k] as string:"";
const nullable=(r:D1Row,k:string)=>typeof r[k]==="string"?r[k] as string:null;
export const birthday=(r:D1Row):Birthday=>({id:str(r,"id"),slug:str(r,"slug"),childName:str(r,"child_name"),birthdayDate:str(r,"birthday_date"),partyDate:str(r,"party_date"),startTime:str(r,"start_time"),invitationText:str(r,"invitation_text"),locationText:str(r,"location_text"),mapsUrl:nullable(r,"maps_url"),phone:nullable(r,"phone"),childImageUrl:nullable(r,"child_image_url"),adminSecret:str(r,"admin_secret"),createdAt:str(r,"created_at"),updatedAt:str(r,"updated_at")});
export const gift=(r:D1Row):Gift=>({id:str(r,"id"),birthdayId:str(r,"birthday_id"),title:str(r,"title"),url:str(r,"url"),imageUrl:nullable(r,"image_url"),priceText:nullable(r,"price_text"),retailer:str(r,"retailer") as Gift["retailer"],sortOrder:typeof r.sort_order==="number"?r.sort_order:Number(r.sort_order)||0,claimedAt:nullable(r,"claimed_at"),claimedByEmail:nullable(r,"claimed_by_email"),claimedWithEmail:nullable(r,"claimed_with_email"),createdAt:str(r,"created_at"),updatedAt:str(r,"updated_at")});
export async function getBirthdayBySlug(slug:string):Promise<Birthday|null>{const {results}=await query("SELECT * FROM birthdays WHERE slug = ? LIMIT 1",[slug]);return results[0]?birthday(results[0]):null}
export async function publicPageData(slug:string):Promise<{birthday:PublicBirthday;gifts:PublicGift[]}|null>{const row=await getBirthdayBySlug(slug);if(!row)return null;const safe:PublicBirthday={id:row.id,slug:row.slug,childName:row.childName,birthdayDate:row.birthdayDate,partyDate:row.partyDate,startTime:row.startTime,invitationText:row.invitationText,locationText:row.locationText,mapsUrl:row.mapsUrl,phone:row.phone,childImageUrl:row.childImageUrl,createdAt:row.createdAt,updatedAt:row.updatedAt};const {results}=await query("SELECT id,birthday_id,title,url,image_url,price_text,retailer,sort_order,claimed_at,created_at,updated_at FROM gifts WHERE birthday_id = ? ORDER BY sort_order,id",[row.id]);return {birthday:safe,gifts:results.map(r=>{const g=gift(r);return {id:g.id,birthdayId:g.birthdayId,title:g.title,url:g.url,imageUrl:g.imageUrl,priceText:g.priceText,retailer:g.retailer,sortOrder:g.sortOrder,claimedAt:g.claimedAt,createdAt:g.createdAt,updatedAt:g.updatedAt}})}}
export async function adminGifts(birthdayId:string){const {results}=await query("SELECT * FROM gifts WHERE birthday_id = ? ORDER BY sort_order,id",[birthdayId]);return results.map(gift)}
export async function claimGift(giftId:string,email:string,coBuyerEmail:string|null=null){const now=new Date().toISOString();const {results}=await query("UPDATE gifts SET claimed_at = ?, claimed_by_email = ?, claimed_with_email = ?, updated_at = ? WHERE id = ? AND claimed_at IS NULL RETURNING id",[now,email,coBuyerEmail,now,giftId]);return results.length>0}
export async function insertBirthday(input:{slug:string;adminSecret:string;childName:string;birthdayDate:string;partyDate:string;startTime:string;invitationText:string;locationText:string;mapsUrl:string|null;phone:string|null;childImageUrl:string|null}){const id=randomUUID(),now=new Date().toISOString();await query("INSERT INTO birthdays (id,slug,child_name,birthday_date,party_date,start_time,invitation_text,location_text,maps_url,phone,child_image_url,admin_secret,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[id,input.slug,input.childName,input.birthdayDate,input.partyDate,input.startTime,input.invitationText,input.locationText,input.mapsUrl,input.phone,input.childImageUrl,input.adminSecret,now,now]);return {id,slug:input.slug}}
