"use server";
import {randomBytes,randomUUID} from "node:crypto";import {revalidatePath} from "next/cache";import {query} from "@/lib/database";import {getBirthdayBySlug} from "@/lib/birthdays";import {birthdaySchema,giftSchema} from "@/lib/validation";import {z} from "zod";
async function authorized(slug:string,key:string){const b=await getBirthdayBySlug(slug);return b&&key.length>20&&key===b.adminSecret?b:null}
export async function updateBirthday(slug:string,key:string,input:unknown){const b=await authorized(slug,key);if(!b)return {ok:false,error:"unauthorized"};const p=birthdaySchema.safeParse(input);if(!p.success)return {ok:false,error:"invalid"};const x=p.data;try{await query("UPDATE birthdays SET child_name=?,birthday_date=?,party_date=?,start_time=?,invitation_text=?,location_text=?,maps_url=?,phone=?,child_image_url=?,updated_at=? WHERE id=?",[x.childName,x.birthdayDate,x.partyDate,x.startTime,x.invitationText,x.locationText,x.mapsUrl||null,x.phone||null,x.childImageUrl||null,new Date().toISOString(),b.id]);revalidatePath(`/${slug}`);revalidatePath(`/${slug}/admin`);return {ok:true}}catch{return {ok:false,error:"database"}}}
export async function saveGift(slug:string,key:string,input:unknown,id?:string){const b=await authorized(slug,key);if(!b)return {ok:false,error:"unauthorized"};const p=giftSchema.safeParse(input);if(!p.success)return {ok:false,error:"invalid"};const x=p.data,now=new Date().toISOString();try{if(id){await query("UPDATE gifts SET title=?,url=?,image_url=?,price_text=?,retailer=?,updated_at=? WHERE id=? AND birthday_id=?",[x.title,x.url,x.imageUrl||null,x.priceText||null,x.retailer,now,id,b.id])}else{const {results}=await query<{max_order:number|null}>("SELECT MAX(sort_order) AS max_order FROM gifts WHERE birthday_id=?",[b.id]);const next=Number(results[0]?.max_order??0)+10;await query("INSERT INTO gifts (id,birthday_id,title,url,image_url,price_text,retailer,sort_order,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)",[randomUUID(),b.id,x.title,x.url,x.imageUrl||null,x.priceText||null,x.retailer,next,now,now])}revalidatePath(`/${slug}`);revalidatePath(`/${slug}/admin`);return {ok:true}}catch{return {ok:false,error:"database"}}}
export async function deleteGift(slug:string,key:string,id:string){const b=await authorized(slug,key);if(!b)return {ok:false};try{await query("DELETE FROM gifts WHERE id=? AND birthday_id=?",[id,b.id]);revalidatePath(`/${slug}`);revalidatePath(`/${slug}/admin`);return {ok:true}}catch{return {ok:false}}}
export async function unclaimGift(slug:string,key:string,id:string){const b=await authorized(slug,key);if(!b)return {ok:false};try{await query("UPDATE gifts SET claimed_at=NULL,claimed_by_email=NULL,claimed_with_email=NULL,updated_at=? WHERE id=? AND birthday_id=?",[new Date().toISOString(),id,b.id]);revalidatePath(`/${slug}`);revalidatePath(`/${slug}/admin`);return {ok:true}}catch{return {ok:false}}}
export async function reorderGifts(slug:string,key:string,input:unknown){const b=await authorized(slug,key);if(!b)return {ok:false};const parsed=z.array(z.string().uuid()).min(1).safeParse(input);if(!parsed.success||new Set(parsed.data).size!==parsed.data.length)return {ok:false};try{const {results}=await query<{id:string}>("SELECT id FROM gifts WHERE birthday_id=? ORDER BY sort_order,id",[b.id]);const currentIds=new Set(results.map(g=>g.id));if(parsed.data.length!==currentIds.size||parsed.data.some(id=>!currentIds.has(id)))return {ok:false};const orderJson=JSON.stringify(parsed.data.map((id,index)=>({id,sortOrder:(index+1)*10})));await query("UPDATE gifts SET sort_order=(SELECT json_extract(value,'$.sortOrder') FROM json_each(?) WHERE json_extract(value,'$.id')=gifts.id),updated_at=? WHERE birthday_id=? AND id IN (SELECT json_extract(value,'$.id') FROM json_each(?))",[orderJson,new Date().toISOString(),b.id,orderJson]);revalidatePath(`/${slug}/admin`);revalidatePath(`/${slug}`);return {ok:true}}catch{return {ok:false}}}
export async function clearReservationData(slug:string,key:string){const b=await authorized(slug,key);if(!b)return {ok:false};try{await query("UPDATE gifts SET claimed_by_email=NULL,claimed_with_email=NULL,updated_at=? WHERE birthday_id=?",[new Date().toISOString(),b.id]);revalidatePath(`/${slug}/admin`);return {ok:true}}catch{return {ok:false}}}
export async function createBirthday(input:unknown){const p=birthdaySchema.safeParse(input);if(!p.success)return {ok:false as const,error:"invalid" as const};try{const f=p.data,slug=`${f.childName.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,42)||"birthday"}-${randomBytes(3).toString("hex")}`,key=randomBytes(32).toString("base64url");await query("INSERT INTO birthdays (id,slug,child_name,birthday_date,party_date,start_time,invitation_text,location_text,maps_url,phone,child_image_url,admin_secret,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[randomUUID(),slug,f.childName,f.birthdayDate,f.partyDate,f.startTime,f.invitationText,f.locationText,f.mapsUrl||null,f.phone||null,f.childImageUrl||null,key,new Date().toISOString(),new Date().toISOString()]);return {ok:true as const,slug,key}}catch{return {ok:false as const,error:"database" as const}}}
